name: WebappBT build test

on: [push, workflow_dispatch]


env:
  RESOURCE-GROUP: rg-webapp-BT
  LOCATION: westeurope
  TEMPLATE-FILE: infra/webapp.tf
  SUBSCRIPTION-ID: ffd83f72-93a8-454d-9e4f-ef231298f429
  WEBAPP-NAME: sistema-webapp-BT
  
jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
    - name: Build with dotnet
      run: dotnet build ./SoftwareTravis.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./SoftwareTravis.sln --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish ./src/Web/Web.csproj -c Release -o ${{'env.DOTNET_ROOT'}}/myapp
        cd ${'env.DOTNET_ROOT'}}}/myapp
        zip -r ../app.zip .
